/**
 * Agribusiness brand system: Evergreen primary, Harvest Gold emphasis, Rice
 * Canvas surfaces, and Slate Leaf copy. Every member role shares these tokens.
 */
import { Link } from "@tanstack/react-router";
import type { AccountRole, MemberProfile } from "@/lib/member";
import { WorkspaceWorkbench } from "@/components/dashboard/WorkspaceWorkbench";

type Action = { title: string; description: string; icon: string; to: string; label: string };
type RoleConfig = {
  label: string;
  eyebrow: string;
  headline: string;
  description: string;
  actions: Action[];
  focus: { icon: string; label: string; text: string }[];
};

const ROLE_WORKSPACES: Record<AccountRole, RoleConfig> = {
  student: {
    label: "Student / Researcher", eyebrow: "Research and opportunity workspace", headline: "Build a profile that connects your study to the sector.", description: "Use your disciplines, research interests, and project portfolio to find relevant people, placements, and learning opportunities.",
    actions: [{ title: "Complete research profile", description: "Add research interests, methods, and academic work.", icon: "biotech", to: "/profile/me", label: "Edit profile" }, { title: "Find internships", description: "Explore companies and project opportunities aligned to your field.", icon: "work", to: "/projects", label: "Explore projects" }, { title: "Continue learning", description: "Access agricultural courses, workshops, and research resources.", icon: "school", to: "/apps/education", label: "Open education" }],
    focus: [{ icon: "science", label: "Research profile", text: "Your profile is the starting point for academic and field connections." }, { icon: "groups", label: "Relevant people", text: "Discover consultants, companies, and researchers in your chosen disciplines." }, { icon: "assignment", label: "Portfolio", text: "Keep projects, skills, and outcomes ready to share when an opportunity arrives." }],
  },
  farmer: {
    label: "Farmer / Producer", eyebrow: "Farm and market workspace", headline: "Make your next field decision with the right support.", description: "Manage your farm details, publish genuine produce offers, discover verified advisors, and share real operational needs.",
    actions: [{ title: "Complete farm profile", description: "Add crops, acreage, livestock, and farm location.", icon: "agriculture", to: "/profile/me", label: "Edit profile" }, { title: "Publish produce", description: "Create a real product listing under your producer account.", icon: "inventory_2", to: "/apps/agri-biz", label: "Open marketplace" }, { title: "Post a farm need", description: "Request practical support for irrigation, crop, machinery, or inputs.", icon: "edit_note", to: "/projects", label: "Post a need" }],
    focus: [{ icon: "agriculture", label: "Farm record", text: "Accurate crops, acreage, and location make discovery more relevant." }, { icon: "monitoring", label: "Market watch", text: "Use current market information as context for selling and buying decisions." }, { icon: "support_agent", label: "Advisory access", text: "Connect with consultants for crop, irrigation, soil, and business support." }],
  },
  buyer: {
    label: "Buyer / Trader / Miller", eyebrow: "Procurement and supply workspace", headline: "Source the right commodity from the right producer.", description: "Define procurement needs, find verified producers, monitor relevant supply, and manage buyer relationships without exposing contact details publicly.",
    actions: [{ title: "Complete procurement profile", description: "Add commodities, grades, buying regions, and expected volume.", icon: "shopping_cart", to: "/profile/me", label: "Edit buyer profile" }, { title: "Post buying requirement", description: "Publish a real commodity requirement for suitable producers.", icon: "playlist_add", to: "/dashboard", label: "Post requirement" }, { title: "Find producers", description: "Search the network for relevant verified farmers and suppliers.", icon: "person_search", to: "/search", label: "Discover producers" }],
    focus: [{ icon: "inventory", label: "Procurement profile", text: "Commodity, grade, volume, and collection area make buyer requirements relevant." }, { icon: "local_shipping", label: "Supply movement", text: "Define delivery regions and logistics requirements before issuing a buying request." }, { icon: "handshake", label: "Verified sourcing", text: "Use consented connections to move from discovery to a private commercial conversation." }],
  },
  consultant: {
    label: "Consultant / Researcher", eyebrow: "Professional services workspace", headline: "Turn specialist knowledge into valuable field work.", description: "Present verified professional information, publish real services, and submit considered proposals to relevant project owners.",
    actions: [{ title: "Complete professional profile", description: "Define services, qualifications, technologies, and availability.", icon: "workspace_premium", to: "/profile/me", label: "Edit profile" }, { title: "Browse projects", description: "Review open briefs and submit a considered proposal.", icon: "description", to: "/projects", label: "View projects" }, { title: "Offer a service", description: "Create a marketplace listing for advisory or technical support.", icon: "add_business", to: "/apps/agri-biz", label: "Create listing" }],
    focus: [{ icon: "verified", label: "Professional trust", text: "Keep degree, experience, field specialism, and public profile information current." }, { icon: "handshake", label: "Relevant requests", text: "Use categories and keywords to surface farm needs you can actually solve." }, { icon: "folder_open", label: "Case work", text: "Build a portfolio of genuine work without exposing confidential client information." }],
  },
  company: {
    label: "Company / Organization", eyebrow: "Organization workspace", headline: "Place the right opportunity in front of the right people.", description: "Manage the accountable company profile, services, technologies, opportunities, and product or service offers from one workspace.",
    actions: [{ title: "Complete company profile", description: "Add company services, technologies, locations, and team details.", icon: "domain", to: "/profile/me", label: "Edit company profile" }, { title: "Create an opportunity", description: "Publish an internship, contract, project, or buyer requirement.", icon: "campaign", to: "/projects", label: "Post opportunity" }, { title: "List products or services", description: "Present a genuine offer to relevant marketplace users.", icon: "inventory_2", to: "/apps/agri-biz", label: "Create listing" }],
    focus: [{ icon: "hub", label: "Service coverage", text: "Make the places, categories, and technologies you serve easy to understand." }, { icon: "groups", label: "Talent and partners", text: "Reach consultants, researchers, and students through relevant work posts." }, { icon: "ads_click", label: "Targeted visibility", text: "Use category and location campaigns only after the company profile is complete." }],
  },
};

function initials(name: string) {
  return name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "AB";
}

export function RoleWorkspace({ profile, onSignOut }: { profile: MemberProfile; onSignOut: () => void }) {
  const config = ROLE_WORKSPACES[profile.user_type];
  const fullName = profile.display_name || profile.full_name || profile.email.split("@")[0];
  const trialEnd = profile.trial_ends_at ? new Intl.DateTimeFormat("en-PK", { day: "numeric", month: "short" }).format(new Date(profile.trial_ends_at)) : null;
  const navigation = [{ icon: "dashboard", label: "Overview", to: "/dashboard" as const }, { icon: "account_circle", label: "My profile", to: "/profile/me" as const }, { icon: "group_add", label: "Connections", to: "/dashboard" as const }, { icon: "search", label: "Discover", to: "/search" as const }, { icon: "work", label: "Projects", to: "/projects" as const }, { icon: "storefront", label: "Marketplace", to: "/apps/agri-biz" as const }];

  return <div className="min-h-screen bg-background text-on-background"><div className="pointer-events-none fixed inset-0 opacity-40" style={{ backgroundImage: "linear-gradient(rgba(15,81,50,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(15,81,50,0.06) 1px, transparent 1px)", backgroundSize: "42px 42px", maskImage: "linear-gradient(to bottom, black, transparent 72%)" }} /><div className="relative flex min-h-screen">
    <aside className="fixed inset-y-0 z-20 hidden w-[268px] flex-col bg-primary text-on-primary lg:flex"><div className="border-b border-white/10 p-7"><Link to="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-secondary text-primary"><span className="material-symbols-outlined text-[25px]">spa</span></span><div><p className="font-display text-[21px] leading-none">AgriBusiness</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.17em] text-secondary-container">Member workspace</p></div></Link></div><div className="p-5 pt-7"><div className="rounded-2xl border border-white/15 bg-white/[0.06] p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-xs font-black text-primary">{initials(fullName)}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{fullName}</p><p className="mt-0.5 truncate text-[10px] text-white/65">{config.label}</p></div></div><p className="mt-4 text-[10px] leading-5 text-white/65">Add genuine profile information to improve how the right people find you.</p></div></div><nav className="space-y-1 px-4 text-xs font-bold">{navigation.map((item, index) => <Link key={item.label} to={item.to} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${index === 0 ? "bg-secondary text-primary" : "text-white/65 transition hover:bg-white/[0.08] hover:text-white"}`}><span className="material-symbols-outlined text-[18px]">{item.icon}</span>{item.label}</Link>)}</nav><div className="mt-auto border-t border-white/10 p-5"><button onClick={onSignOut} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-bold text-white/65 transition hover:bg-white/[0.08] hover:text-white"><span className="material-symbols-outlined text-[18px]">logout</span>Sign out</button></div></aside>
    <main className="relative z-10 min-w-0 flex-1 lg:ml-[268px]"><header className="flex h-[74px] items-center justify-between border-b border-outline-variant/70 bg-background/95 px-5 backdrop-blur-xl md:px-8"><Link to="/" className="flex items-center gap-2 lg:hidden"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-secondary"><span className="material-symbols-outlined text-[19px]">spa</span></span><span className="font-display text-lg text-primary">AgriBusiness</span></Link><Link to="/search" className="hidden items-center gap-2 rounded-full border border-outline-variant/70 bg-white px-4 py-2.5 text-xs text-on-surface-variant transition hover:border-primary/40 md:flex"><span className="material-symbols-outlined text-[17px]">search</span>Discover people, services, projects…</Link><div className="ml-auto flex items-center gap-3">{trialEnd ? <span className="hidden items-center gap-1.5 rounded-full bg-secondary-container px-3 py-1.5 text-[10px] font-bold text-on-secondary-container sm:inline-flex"><span className="material-symbols-outlined text-[14px]">schedule</span>Trial through {trialEnd}</span> : null}<Link to="/profile/me" className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xs font-black text-on-primary shadow-sm">{initials(fullName)}</Link></div></header>
          <section className="mx-auto max-w-[1500px] px-5 pb-16 pt-7 md:px-8 lg:px-10"><div className="mb-7 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div className="max-w-3xl"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-primary"><span className="material-symbols-outlined text-[14px]">{profile.user_type === "farmer" ? "agriculture" : profile.user_type === "buyer" ? "shopping_cart" : profile.user_type === "student" ? "school" : profile.user_type === "consultant" ? "workspace_premium" : "domain"}</span>{config.label}</div><h1 className="font-display text-3xl leading-[1.06] tracking-[-0.035em] text-primary md:text-[43px]">{config.headline}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-on-surface-variant">{config.description}</p></div><Link to={config.actions[0].to} className="inline-flex w-fit items-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-on-primary shadow-[0_12px_28px_rgba(15,81,50,0.16)] transition hover:bg-primary-container"><span className="material-symbols-outlined text-[17px]">arrow_forward</span>{config.actions[0].label}</Link></div>
        <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.7fr)]"><div className="space-y-5"><section className="overflow-hidden rounded-2xl border border-outline-variant/60 bg-white shadow-[0_10px_28px_rgba(15,81,50,0.06)]"><div className="relative overflow-hidden bg-primary p-6 md:p-8"><div className="absolute right-0 top-0 h-52 w-52 -translate-y-10 translate-x-10 rounded-full border border-white/15" /><div className="absolute bottom-0 right-24 h-32 w-32 rounded-full border border-white/10" /><div className="relative max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-secondary-container">Your next best moves</p><h2 className="mt-2 font-display text-3xl text-on-primary">Set your workspace up for real opportunities.</h2><p className="mt-3 text-sm leading-6 text-white/75">These role-specific actions create real records under your account and help others understand how to work with you.</p></div></div><div className="grid divide-y divide-outline-variant/50 md:grid-cols-3 md:divide-x md:divide-y-0">{config.actions.map((action) => <Link key={action.title} to={action.to} className="group p-5 transition hover:bg-surface-container-low"><span className="material-symbols-outlined text-[23px] text-primary">{action.icon}</span><h3 className="mt-4 text-sm font-bold text-primary">{action.title}</h3><p className="mt-2 text-[11px] leading-5 text-on-surface-variant">{action.description}</p><span className="mt-4 inline-flex items-center gap-1 text-[10px] font-bold text-primary">{action.label}<span className="material-symbols-outlined text-[13px] transition-transform group-hover:translate-x-1">arrow_forward</span></span></Link>)}</div></section>
            <section className="rounded-2xl border border-outline-variant/60 bg-white p-5 shadow-[0_10px_28px_rgba(15,81,50,0.06)] md:p-7"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-on-surface-variant/65">Your workspace focus</p><h2 className="mt-1 font-display text-2xl text-primary">Build relevance over time</h2></div><Link to="/profile/me" className="text-xs font-bold text-primary">Edit profile</Link></div><div className="mt-5 divide-y divide-outline-variant/40">{config.focus.map((item) => <div className="flex gap-4 py-4" key={item.label}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary-container text-on-secondary-container"><span className="material-symbols-outlined text-[19px]">{item.icon}</span></span><div><p className="text-sm font-bold text-primary">{item.label}</p><p className="mt-1 text-[11px] leading-5 text-on-surface-variant">{item.text}</p></div></div>)}</div></section><WorkspaceWorkbench profile={profile} /></div>
          <aside className="space-y-5"><section className="rounded-2xl border border-outline-variant/60 bg-white p-5 shadow-[0_10px_28px_rgba(15,81,50,0.06)]"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-on-surface-variant/65">Account status</p><div className="mt-4 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary text-on-primary"><span className="material-symbols-outlined">person</span></span><div><p className="text-sm font-bold text-primary">{fullName}</p><p className="mt-1 text-[10px] text-on-surface-variant">{profile.city || "Location not set"} · {config.label}</p></div></div><div className="mt-5 rounded-xl border border-outline-variant/55 bg-surface-container-low p-3 text-[11px] leading-5 text-on-surface-variant"><span className="font-bold text-primary">Plan:</span> {profile.subscription_status || "Not configured"}. Keep your profile current to receive relevant introductions.</div></section><section className="rounded-2xl border border-outline-variant/60 bg-white p-5 shadow-[0_10px_28px_rgba(15,81,50,0.06)]"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-on-surface-variant/65">Discover the network</p><h2 className="mt-1 font-display text-2xl text-primary">Find relevant people, not noise.</h2><p className="mt-3 text-[11px] leading-5 text-on-surface-variant">Search by category, discipline, service, technology, and location to find people who are relevant to your work.</p><Link to="/search" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-outline-variant/70 py-2.5 text-xs font-bold text-primary transition hover:bg-surface-container-low"><span className="material-symbols-outlined text-[16px]">search</span>Discover people</Link></section></aside></div>
      </section></main></div></div>;
}
