/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsAgriBizRouteImport } from './routes/apps/agri-biz'
import { Route as AppsAnimalClinicRouteImport } from './routes/apps/animal-clinic'
import { Route as AppsPlantClinicRouteImport } from './routes/apps/plant-clinic'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAgriBizRoute = AppsAgriBizRouteImport.update({
  id: '/apps/agri-biz',
  path: '/apps/agri-biz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAnimalClinicRoute = AppsAnimalClinicRouteImport.update({
  id: '/apps/animal-clinic',
  path: '/apps/animal-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPlantClinicRoute = AppsPlantClinicRouteImport.update({
  id: '/apps/plant-clinic',
  path: '/apps/plant-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/apps': typeof AppsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/feed'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/rates'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin/'
    | '/apps/'
    | '/categories/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/feed'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/rates'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin'
    | '/apps'
    | '/categories'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/feed'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/rates'
    | '/reset-password'
    | '/resources'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin/'
    | '/apps/'
    | '/categories/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RatesRoute: typeof RatesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  AppsAgriBizRoute: typeof AppsAgriBizRoute
  AppsAnimalClinicRoute: typeof AppsAnimalClinicRoute
  AppsPlantClinicRoute: typeof AppsPlantClinicRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/agri-biz': {
      id: '/apps/agri-biz'
      path: '/apps/agri-biz'
      fullPath: '/apps/agri-biz'
      preLoaderRoute: typeof AppsAgriBizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/animal-clinic': {
      id: '/apps/animal-clinic'
      path: '/apps/animal-clinic'
      fullPath: '/apps/animal-clinic'
      preLoaderRoute: typeof AppsAnimalClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/plant-clinic': {
      id: '/apps/plant-clinic'
      path: '/apps/plant-clinic'
      fullPath: '/apps/plant-clinic'
      preLoaderRoute: typeof AppsPlantClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RatesRoute: RatesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  AppsAgriBizRoute: AppsAgriBizRoute,
  AppsAnimalClinicRoute: AppsAnimalClinicRoute,
  AppsPlantClinicRoute: AppsPlantClinicRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
